DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS vendors CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS inboxes CASCADE;
DROP TABLE IF EXISTS chats CASCADE;
DROP TABLE IF EXISTS chat_messages CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  hashed_password VARCHAR(255) NOT NULL,
  profile_photo_url VARCHAR(255) NOT NULL,
  admin_status BOOLEAN, 
  inbox_id INTEGER REFERENCES inboxes(id) ON DELETE CASCADE
);

CREATE TABLE vendors (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  bio VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  longitude DECIMAL NOT NULL,
  latitude DECIMAL NOT NULL,
  vendor_logo_url VARCHAR(255) NOT NULL,
  admin_user INTEGER REFERENCES users(id) ON DELETE CASCADE,
  inbox_id INTEGER REFERENCES inboxes(id) ON DELETE CASCADE
);

CREATE TABLE products (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  photo_url VARCHAR(255) NOT NULL,
  inventory SMALLINT,
  price_cents INTEGER,
  vendor_id INTEGER REFERENCES vendors(id) ON DELETE CASCADE,
  category VARCHAR(255) NOT NULL
);

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  time_ordered TIMESTAMPZ DEFAULT CURRENT_TIMESTAMP,
  total_cost INTERGER
);

CREATE TABLE order_items (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
  quantity INTEGER
);

CREATE TABLE inboxes (
  id SERIAL PRIMARY KEY NOT NULL,
  chat_id INTEGER REFERENCES chats(id) ON DELETE CASCADE,
);

CREATE TABLE chats (
  id SERIAL PRIMARY KEY NOT NULL,
  inbox_id INTEGER REFERENCES inboxes(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  contact_user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  last_message VARCHAR(1000) NOT NULL
);

CREATE TABLE chat_messages (
  id SERIAL PRIMARY KEY NOT NULL,
  message VARCHAR(1000) NOT NULL,
  created_at TIMESTAMPZ DEFAULT CURRENT_TIMESTAMP,
  sender_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  chat_id INTEGER REFERENCES chats(id) ON DELETE CASCADE,
);

